### ISSUE TITLE
Balance per <tr> seems not correct

### ISSUE THREAD

**Issue by spielhoelle** [flophub/docs#16]
In [this line](https://github.com/flophub/ui/blob/c4f80fd49c45f438b0d6b8c1126403c6771434c5/src/routes/dashboard/+page.svelte#L511), it seems not to be the right calculation

![Image](https://github.com/flophub/docs/assets/6317641/c941a924-d26a-47a0-9a66-1561611ee896)

ETA: 1h

**Comment by colinwilliams91** [comment]
Is this supposed to be in the [docs repo](https://github.com/flophub/docs)?
