### ISSUE TITLE
terminate button leads to error screen and does not terminate the node due to a price ceiling not being met, unless you wait 5 minutes before terminating, also there is hanging tooltip

### ISSUE THREAD

**Issue by skiwheelr** [flophub/docs#19]
also need to remove tooltip that hangs

**Comment by skiwheelr** [comment]
changed 'Sure?' to ask them to wait for 30 seconds

**Comment by skiwheelr** [comment]
branch is called terminateCeiling

**Comment by rocalex** [comment]
need to show user the message that usage amount should be greater than $0.01 before termination.

**Comment by rocalex** [comment]
In addition, when you test it in local machine, database should have the owner data of node.

**Comment by skiwheelr** [comment]
@spielhoelle we need to verify that this does the correct thing with stripe
